name: downloader
on:
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    

    - name: Download
      run: |
        mkdir final
        cd final
        wget https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Final
        path: ./final/*
